# Generated by Django 5.2.3 on 2025-06-11 16:26

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiml_app', '0002_user_address_user_country_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Participant'), (3, 'Author'), (4, 'Speaker')], null=True),
        ),
    ]
